name: testing
on: 
    push:
        branches: 
            - main
            - dev
    workflow_dispatch:        
jobs:
    testing:
        name: needs to trigger when pushed to main branch
        if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - name: get-code
              uses: actions/checkout@v3
            - name: test
              run: npm ci
    lint:
        name: this will triggers when pushed to dev branch
        if: github.ref == 'refs/heads/dev'
        runs-on: ubuntu-latest
        steps:
            - name: get-code
              uses: actions/checkout@v3
            - name: test
              run: npm run test           